name = "mendraw"
version = "2.1.0"
gleam = ">= 1.17.0"
target = "javascript"
description = "Typed Mendix client values and bindings for installed MPK widget assets"
licences = ["MIT"]
repository = { type = "github", user = "glendix-labs", repo = "mendraw" }

[javascript]
typescript_declarations = false
runtime = "node"

[dependencies]
gleam_stdlib = ">= 1.0.3 and < 2.0.0"
redraw = ">= 19.2.2 and < 20.0.0"
redraw_dom = ">= 19.2.2 and < 20.0.0"

[dev_dependencies]
gleeunit = ">= 1.11.0 and < 2.0.0"
